/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE Dim_Agente_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Dim_Agente_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Dim_Campana_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Dim_Campana_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Dim_Estado_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Dim_Estado_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Dim_Fecha_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Dim_Fecha_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Dim_Geografia_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Dim_Geografia_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Dim_Proveedor_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Dim_Proveedor_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Dim_sucursal_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Dim_sucursal_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Fac_Estadoagente_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Fac_Estadoagente_Id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE Fac_Llamada_Id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE Fac_Llamada_Id_seq IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: Dim_Agente ************************/

/* Build Table Structure */
CREATE TABLE Dim_Agente
(
	Id INTEGER DEFAULT nextval('public.Dim_Agente_Id_seq'::regclass) NOT NULL,
	nombre VARCHAR NOT NULL,
	genero VARCHAR NOT NULL,
	fecha_nacimiento TIMESTAMP NULL,
	numdocumento BIGINT NOT NULL
);

/* Add Primary Key */
ALTER TABLE Dim_Agente ADD CONSTRAINT pkDim_Agente
	PRIMARY KEY (Id);


/******************** Add Table: Dim_Campana ************************/

/* Build Table Structure */
CREATE TABLE Dim_Campana
(
	Id INTEGER DEFAULT nextval('public.Dim_Campana_Id_seq'::regclass) NOT NULL,
	nombre VARCHAR NOT NULL,
	cliente VARCHAR NOT NULL
);

/* Add Primary Key */
ALTER TABLE Dim_Campana ADD CONSTRAINT pkDim_Campana
	PRIMARY KEY (Id);


/******************** Add Table: Dim_Estado ************************/

/* Build Table Structure */
CREATE TABLE Dim_Estado
(
	Id INTEGER DEFAULT nextval('public.Dim_Estado_Id_seq'::regclass) NOT NULL,
	estado VARCHAR NOT NULL
);

/* Add Primary Key */
ALTER TABLE Dim_Estado ADD CONSTRAINT pkDim_Estado
	PRIMARY KEY (Id);


/******************** Add Table: Dim_Fecha ************************/

/* Build Table Structure */
CREATE TABLE Dim_Fecha
(
	Id INTEGER DEFAULT nextval('public.Dim_Fecha_Id_seq'::regclass) NOT NULL,
	hora INTEGER NOT NULL,
	dia BIGINT NOT NULL,
	dia_semana VARCHAR NOT NULL,
	mes INTEGER NOT NULL,
	anho INTEGER NOT NULL,
	mes_nombre VARCHAR NOT NULL,
	fecha TIMESTAMP NOT NULL
);

/* Add Primary Key */
ALTER TABLE Dim_Fecha ADD CONSTRAINT pkDim_Fecha
	PRIMARY KEY (Id);


/******************** Add Table: Dim_Geografia ************************/

/* Build Table Structure */
CREATE TABLE Dim_Geografia
(
	Id INTEGER DEFAULT nextval('public.Dim_Geografia_Id_seq'::regclass) NOT NULL,
	pais VARCHAR NOT NULL,
	departamento VARCHAR NULL,
	ciudad VARCHAR NULL
);

/* Add Primary Key */
ALTER TABLE Dim_Geografia ADD CONSTRAINT pkDim_Geografia
	PRIMARY KEY (Id);


/******************** Add Table: Dim_Proveedor ************************/

/* Build Table Structure */
CREATE TABLE Dim_Proveedor
(
	Id INTEGER DEFAULT nextval('public.Dim_Proveedor_Id_seq'::regclass) NOT NULL,
	nombre VARCHAR NOT NULL
);

/* Add Primary Key */
ALTER TABLE Dim_Proveedor ADD CONSTRAINT pkDim_Proveedor
	PRIMARY KEY (Id);


/******************** Add Table: Dim_sucursal ************************/

/* Build Table Structure */
CREATE TABLE Dim_sucursal
(
	Id INTEGER DEFAULT nextval('public.Dim_sucursal_Id_seq'::regclass) NOT NULL,
	nombre VARCHAR NOT NULL
);

/* Add Primary Key */
ALTER TABLE Dim_sucursal ADD CONSTRAINT pkDim_sucursal
	PRIMARY KEY (Id);


/******************** Add Table: Fac_Estadoagente ************************/

/* Build Table Structure */
CREATE TABLE Fac_Estadoagente
(
	Id INTEGER DEFAULT nextval('public.Fac_Estadoagente_Id_seq'::regclass) NOT NULL,
	Dim_Agente_Id INTEGER NULL,
	Dim_Estado_Id INTEGER NULL,
	Dim_Fecha_Id INTEGER NULL,
	Dim_sucursal_Id INTEGER NULL
);

/* Add Primary Key */
ALTER TABLE Fac_Estadoagente ADD CONSTRAINT pkFac_Estadoagente
	PRIMARY KEY (Id);


/******************** Add Table: Fac_Llamada ************************/

/* Build Table Structure */
CREATE TABLE Fac_Llamada
(
	Id INTEGER DEFAULT nextval('public.Fac_Llamada_Id_seq'::regclass) NOT NULL,
	Dim_Fecha_Id INTEGER NULL,
	cantidad INTEGER NOT NULL,
	segundos INTEGER NOT NULL,
	Dim_sucursal_Id INTEGER NULL,
	Dim_Geografia_Id INTEGER NULL,
	Dim_Campana_Id INTEGER NULL,
	Dim_Agente_Id INTEGER NULL
);

/* Add Primary Key */
ALTER TABLE Fac_Llamada ADD CONSTRAINT pkFac_Llamada
	PRIMARY KEY (Id);





/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_Fac_Estadoagente_Dim_Agente */
ALTER TABLE Fac_Estadoagente ADD CONSTRAINT fk_Fac_Estadoagente_Dim_Agente
	FOREIGN KEY (Dim_Agente_Id) REFERENCES Dim_Agente (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Estadoagente_Dim_Estado */
ALTER TABLE Fac_Estadoagente ADD CONSTRAINT fk_Fac_Estadoagente_Dim_Estado
	FOREIGN KEY (Dim_Estado_Id) REFERENCES Dim_Estado (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Estadoagente_Dim_Fecha */
ALTER TABLE Fac_Estadoagente ADD CONSTRAINT fk_Fac_Estadoagente_Dim_Fecha
	FOREIGN KEY (Dim_Fecha_Id) REFERENCES Dim_Fecha (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Estadoagente_Dim_sucursal */
ALTER TABLE Fac_Estadoagente ADD CONSTRAINT fk_Fac_Estadoagente_Dim_sucursal
	FOREIGN KEY (Dim_sucursal_Id) REFERENCES Dim_sucursal (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Llamada_Dim_Agente */
ALTER TABLE Fac_Llamada ADD CONSTRAINT fk_Fac_Llamada_Dim_Agente
	FOREIGN KEY (Dim_Agente_Id) REFERENCES Dim_Agente (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Llamada_Dim_Campana */
ALTER TABLE Fac_Llamada ADD CONSTRAINT fk_Fac_Llamada_Dim_Campana
	FOREIGN KEY (Dim_Campana_Id) REFERENCES Dim_Campana (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Llamada_Dim_Fecha */
ALTER TABLE Fac_Llamada ADD CONSTRAINT fk_Fac_Llamada_Dim_Fecha
	FOREIGN KEY (Dim_Fecha_Id) REFERENCES Dim_Fecha (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Llamada_Dim_Geografia */
ALTER TABLE Fac_Llamada ADD CONSTRAINT fk_Fac_Llamada_Dim_Geografia
	FOREIGN KEY (Dim_Geografia_Id) REFERENCES Dim_Geografia (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_Fac_Llamada_Dim_sucursal */
ALTER TABLE Fac_Llamada ADD CONSTRAINT fk_Fac_Llamada_Dim_sucursal
	FOREIGN KEY (Dim_sucursal_Id) REFERENCES Dim_sucursal (Id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;
